session_name: market-auth
start_directory: .

shell_command_before:
  - >
    [ -d `.venv/bin/activate` ] &&
    source .venv/bin/activate &&
    reset
  - clear

environment:
  TEST: "test"

windows:
  - window_name: nvim
    shell_command_before:
    panes:
      - shell_command:
          - nvim

  - window_name: shell
    panes:
      - shell_command:
          -

  - window_name: tests
    panes:
      - shell_command:
          - cmd: just test
            enter: false

  - window_name: monitoring
    layout: tiled
    panes:
      - shell_command:
          - just up service
          - sleep 0.2
          - just logs auth
      - shell_command:
          - just logs auth-db
      - shell_command:
          - just logs kafka
      - shell_command:
          - just logs redis
