session_name: market-auth
start_directory: .

shell_command_before:
  - >
    [ -d `.venv/bin/activate` ] &&
    source .venv/bin/activate &&
    reset
  - clear

environment:
  TEST: "test"

windows:
  - window_name: nvim
    shell_command_before:
    panes:
      - shell_command:
          - nvim

  - window_name: shell
    panes:
      - shell_command:
          -

  - window_name: empty
    panes:
      - shell_command:
          - pytest .

  - window_name: empty
    panes:
      - shell_command:
          - just up service
