"""add outbox

Revision ID: 8680c7ebf039
Revises: a84999fd3036
Create Date: 2025-10-13 18:37:01.583909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8680c7ebf039'
down_revision: Union[str, Sequence[str], None] = 'a84999fd3036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'PUBLISHING', 'PUBLISHED', 'FAILED', 'DLQ', name='outboxstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('kafka_partition', sa.Integer(), nullable=True),
    sa.Column('kafka_offset', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partial_next_retry_at', 'outbox', ['next_retry_at'], unique=False, postgresql_where=sa.text("status IN ('NEW', 'FAILED')"), postgresql_using='btree')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_partial_next_retry_at', table_name='outbox', postgresql_where=sa.text("status IN ('NEW', 'FAILED')"), postgresql_using='btree')
    op.drop_table('outbox')
    # ### end Alembic commands ###
