"""create refresh token and family

Revision ID: b08a1223de1c
Revises: 8680c7ebf039
Create Date: 2025-10-15 21:11:06.011524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b08a1223de1c'
down_revision: Union[str, Sequence[str], None] = '8680c7ebf039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_families',
    sa.Column('fid', sa.UUID(), nullable=False),
    sa.Column('fingerprint_hash', sa.String(length=256), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Дата и время обновления записи'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fid')
    )
    op.create_index(op.f('ix_refresh_families_account_id'), 'refresh_families', ['account_id'], unique=False)
    op.create_index(op.f('ix_refresh_families_expires_at'), 'refresh_families', ['expires_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('hash', sa.String(length=256), nullable=False),
    sa.Column('rotated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fid', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('rotation_parent_jti', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Дата и время создания записи'),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Дата и время обновления записи'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fid'], ['refresh_families.fid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotation_parent_jti'], ['refresh_tokens.jti'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('jti'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_refresh_tokens_account_id'), 'refresh_tokens', ['account_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_fid'), 'refresh_tokens', ['fid'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_rotation_parent_jti'), 'refresh_tokens', ['rotation_parent_jti'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_rotation_parent_jti'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_fid'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_account_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_refresh_families_expires_at'), table_name='refresh_families')
    op.drop_index(op.f('ix_refresh_families_account_id'), table_name='refresh_families')
    op.drop_table('refresh_families')
    # ### end Alembic commands ###
